name: gcov2lcov-action

description: "convert golang coverage to lcov format"

inputs:
  infile:
    description: "go coverage input file"
    required: false
    default: coverage.out
  outfile:
    description: "lcov output file"
    required: false
    default: coverage.lcov
  version:
    description: "gcov2lcov version"
    required: false
    default: latest
  working-directory:
    description: "change working directory"
    required: false
  github-token:
    description: "GitHub token for API authentication. Defaults to the automatic GitHub token for improved rate limits."
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -xe
        if [ "${{inputs.version}}" == "latest" ]; then
          URL="https://api.github.com/repos/jandelgado/gcov2lcov/releases/latest"
        else
          URL="https://api.github.com/repos/jandelgado/gcov2lcov/releases/tags/${{inputs.version}}"
        fi
        # Build authentication header if token is provided
        if [ -n "${{ inputs.github-token }}" ]; then
          echo "Using authenticated GitHub API requests for improved rate limits"
          # Capture headers and response separately for rate limit logging
          RESPONSE_WITH_HEADERS=$(curl -i -H "Authorization: Bearer ${{ inputs.github-token }}" "$URL")
          # Extract and log rate limit headers
          echo "Rate limit headers from authenticated request:"
          echo "$RESPONSE_WITH_HEADERS" | grep -i "x-ratelimit" || echo "No rate limit headers found"
          # Extract JSON response (skip headers)
          JSON_RESPONSE=$(echo "$RESPONSE_WITH_HEADERS" | sed -n '/^{/,$p')
          PACKAGE_URL=$(echo "$JSON_RESPONSE" | jq -r '[ .assets[] | select(.name | test("gcov2lcov.*linux.amd64.tar.gz")) | .browser_download_url ] | first ')
        else
          echo "Using unauthenticated GitHub API requests"
          # Capture headers and response separately for rate limit logging  
          RESPONSE_WITH_HEADERS=$(curl -i "$URL")
          # Extract and log rate limit headers
          echo "Rate limit headers from unauthenticated request:"
          echo "$RESPONSE_WITH_HEADERS" | grep -i "x-ratelimit" || echo "No rate limit headers found"
          # Extract JSON response (skip headers)
          JSON_RESPONSE=$(echo "$RESPONSE_WITH_HEADERS" | sed -n '/^{/,$p')
          PACKAGE_URL=$(echo "$JSON_RESPONSE" | jq -r '[ .assets[] | select(.name | test("gcov2lcov.*linux.amd64.tar.gz")) | .browser_download_url ] | first ')
        fi
        
        # starting with version v1.1.0 gcov2lcov changed it's artefact naming a bit.
        # we are gentle and support also the old naming convetion
        curl -sLf "$PACKAGE_URL" | tar zxf -
        mv bin/gcov2lcov-linux-amd64 gcov2lcov > /dev/null 2>&1 || true  # before v1.1.0

      working-directory: /tmp
    - shell: bash
      run: 'set -x && GOROOT=$(go env GOROOT) /tmp/gcov2lcov -infile "${{ inputs.infile }}" -outfile "${{ inputs.outfile }}"'
      working-directory: ${{ inputs.working-directory }}
